import 'models/models.dart';

List<LogItem> DUMMY_WORKOUT = [
  LogItem(
    categoryId: 5,
    categoryName: "Chest",
    workoutId: -1,
    workoutName: "",
    weight: 10,
    reps: 3,
    workoutDesc:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam blandit leo at justo iaculis, eget pretium orci sollicitudin. Phasellus non dolor nec ligula gravida vestibulum. Phasellus varius dolor in purus pellentesque tempor. Integer massa libero, vestibulum non eleifend ut, egestas at ligula. Donec tempus mauris eget est scelerisque condimentum.",
    workoutDate: DateTime.now(),
    customWorkoutName: "Bar Press",
    isCustom: 1,
  ),
  LogItem(
    categoryId: 5,
    categoryName: "Chest",
    workoutId: 4,
    workoutName: "Dumbbell flys",
    weight: 5,
    reps: 5,
    workoutDesc:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam blandit leo at justo iaculis, eget pretium orci sollicitudin. Phasellus non dolor nec ligula gravida vestibulum. Phasellus varius dolor in purus pellentesque tempor. Integer massa libero, vestibulum non eleifend ut, egestas at ligula. Donec tempus mauris eget est scelerisque condimentum.",
    workoutDate: DateTime.now(),
    customWorkoutName: "",
    isCustom: 0,
  ),
  LogItem(
    categoryId: 5,
    categoryName: "Chest",
    workoutId: 7,
    workoutName: "Push Ups",
    weight: 0.0,
    reps: 0,
    workoutDesc: "",
    workoutDate: DateTime.now(),
    customWorkoutName: "",
    isCustom: 0,
  ),
  LogItem(
    categoryId: 2,
    categoryName: "Arms",
    workoutId: 1,
    workoutName: "Dumbbell bicep curl",
    weight: 10,
    reps: 5,
    workoutDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    workoutDate: DateTime.now(),
    customWorkoutName: "",
    isCustom: 0,
  ),
  LogItem(
    categoryId: 2,
    categoryName: "Arms",
    workoutId: 3,
    workoutName: "Hammer curl",
    weight: 2.5,
    reps: 5,
    workoutDesc:
        "Phasellus non dolor nec ligula gravida vestibulum. Phasellus varius dolor in purus pellentesque tempor. Integer massa libero, vestibulum non eleifend ut, egestas at ligula. Donec tempus mauris eget est scelerisque condimentum.",
    workoutDate: DateTime.now(),
    customWorkoutName: "",
    isCustom: 0,
  ),
];
